/*
 * This file is generated by the @wordpress/terrazzo-plugin-density-overrides plugin.
 * Do not edit this file directly.
 */

const densityOverrides = {
	default: {
		'--wpds-dimension-gap-2xl': '32px',
		'--wpds-dimension-gap-3xl': '40px',
		'--wpds-dimension-gap-lg': '16px',
		'--wpds-dimension-gap-md': '12px',
		'--wpds-dimension-gap-sm': '8px',
		'--wpds-dimension-gap-xl': '24px',
		'--wpds-dimension-gap-xs': '4px',
		'--wpds-dimension-padding-2xl': '24px',
		'--wpds-dimension-padding-3xl': '32px',
		'--wpds-dimension-padding-lg': '16px',
		'--wpds-dimension-padding-md': '12px',
		'--wpds-dimension-padding-sm': '8px',
		'--wpds-dimension-padding-xl': '20px',
		'--wpds-dimension-padding-xs': '4px',
	},
	compact: {
		'--wpds-dimension-gap-2xl': '24px',
		'--wpds-dimension-gap-3xl': '32px',
		'--wpds-dimension-gap-lg': '12px',
		'--wpds-dimension-gap-md': '8px',
		'--wpds-dimension-gap-sm': '4px',
		'--wpds-dimension-gap-xl': '20px',
		'--wpds-dimension-gap-xs': '4px',
		'--wpds-dimension-padding-2xl': '20px',
		'--wpds-dimension-padding-3xl': '24px',
		'--wpds-dimension-padding-lg': '12px',
		'--wpds-dimension-padding-md': '8px',
		'--wpds-dimension-padding-sm': '4px',
		'--wpds-dimension-padding-xl': '16px',
		'--wpds-dimension-padding-xs': '4px',
	},
	comfortable: {
		'--wpds-dimension-gap-2xl': '40px',
		'--wpds-dimension-gap-3xl': '48px',
		'--wpds-dimension-gap-lg': '20px',
		'--wpds-dimension-gap-md': '16px',
		'--wpds-dimension-gap-sm': '12px',
		'--wpds-dimension-gap-xl': '32px',
		'--wpds-dimension-gap-xs': '8px',
		'--wpds-dimension-padding-2xl': '32px',
		'--wpds-dimension-padding-3xl': '40px',
		'--wpds-dimension-padding-lg': '20px',
		'--wpds-dimension-padding-md': '16px',
		'--wpds-dimension-padding-sm': '12px',
		'--wpds-dimension-padding-xl': '24px',
		'--wpds-dimension-padding-xs': '8px',
	},
} as const;

export type DensityOverrideKey = keyof typeof densityOverrides;

export default densityOverrides;
